server:
  port: 8888

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springboot-application?autoReconnect=true&useSSL=false
  #rabbitmq配置信息
  rabbitmq:
    host:
    port: 5672
    username: rabbitmqtest
    password: rabbitmqtest


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
mybatis:
  mapper-locations: classpath:mapper/*.xml

